version: "3.9"

services:
  bot:
    image: ghcr.io/chidi150c/coinbase-bot:latest
    command: ["-live", "-interval", "1"]
    volumes:
      - /opt/coinbase/env:/opt/coinbase/env:ro
      - /opt/coinbase/state:/opt/coinbase/state
    env_file:
      - /opt/coinbase/env/bot.env
    restart: unless-stopped
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/healthz >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bot, coinbase-bot]

  bridge:
    image: ghcr.io/chidi150c/coinbase-bridge:latest
    env_file:
      - /opt/coinbase/env/bridge.env
    expose:
      - "8787"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8787/health >/dev/null 2>&1 || exit 1"]
      interval: 15s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bridge]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring_network

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - monitoring_grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - bot
      - bridge
    networks:
      - monitoring_network

volumes:
  monitoring_prometheus_data:
  monitoring_grafana_data:
  coinbase_state:

networks:
  monitoring_network:
    driver: bridge
