version: "3.9"

services:
  bot:
    image: golang:1.23
    working_dir: /app
    volumes:
      - ..:/app
    env_file:
      - /opt/coinbase/env/bot.env
    command: /usr/local/go/bin/go run . -live -interval 15
    #command: /usr/local/go/bin/go run . -backtest /app/data/BTC-USD.csv -interval 1
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      monitoring_network:
        aliases: [bot, coinbase-bot]

  bridge:
    image: python:3.11-slim
    working_dir: /app/bridge
    volumes:
      - ../bridge:/app/bridge:ro
    env_file:
      - /opt/coinbase/env/bridge.env
    command: >
      sh -lc "apt-get update && apt-get install -y bash &&
          bash -lc 'pip install --no-cache-dir fastapi uvicorn coinbase-advanced-py python-dotenv &&
                    uvicorn app:app --host 0.0.0.0 --port 8787'"
    expose:
      - "8787"
    restart: unless-stopped
    networks:
      monitoring_network:
        aliases: [bridge]

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - monitoring_grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - bot
      - bridge
    networks:
      - monitoring_network

volumes:
  monitoring_prometheus_data:
  monitoring_grafana_data:

networks:
  monitoring_network:
    driver: bridge
