services:
  bridge_hitbtc:
    build:
      context: ./bridge
      dockerfile: Dockerfile.ws
    container_name: bridge_hitbtc
    environment:
      EXCHANGE: "hitbtc"
      SYMBOL: "BTCUSDT"
      PORT: "8788"
      STALE_MS: "3000"
    networks:
      - monitoring_network
    restart: unless-stopped

  bridge_binance:
    build:
      context: ./bridge
      dockerfile: Dockerfile.ws
    container_name: bridge_binance
    environment:
      EXCHANGE: "binance"
      SYMBOL: "BTCUSDT"
      PORT: "8789"
      STALE_MS: "3000"
    networks:
      - monitoring_network
    restart: unless-stopped

  bridge:
    image: ghcr.io/chidi150c/coinbase-bridge:latest
    env_file:
      - /opt/coinbase/env/bridge.env
    expose:
      - "8787"
    restart: unless-stopped
    healthcheck:
      test: ["NONE"]   # image may not include wget/curl
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bridge]

  
  bot:
    image: ghcr.io/chidi150c/coinbase-bot:latest
    command: ["-live", "-interval", "1"]
    volumes:
      - /opt/coinbase/env:/opt/coinbase/env:ro
      - /opt/coinbase/state:/opt/coinbase/state
    env_file:
      - /opt/coinbase/env/bot.env
      - /opt/coinbase/env/bot_coinbase.env    # <-- NEW: pin Coinbase broker/symbol/state
    restart: unless-stopped
    expose:
      - "8080"
    healthcheck:
      test: ["NONE"]   # distroless image: no shell/curl inside
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bot, coinbase-bot]

  # NEW: second bot instance for Binance
  bot_binance:
    image: ghcr.io/chidi150c/coinbase-bot:latest
    command: ["-live", "-interval", "1"]
    volumes:
      - /opt/coinbase/env:/opt/coinbase/env:ro
      - /opt/coinbase/state:/opt/coinbase/state
    env_file:
      - /opt/coinbase/env/bot.env
      - /opt/coinbase/env/binance.env         # holds BINANCE_API_KEY/SECRET
      - /opt/coinbase/env/bot_binance.env     # broker/product/state overrides for Binance
    restart: unless-stopped
    expose:
      - "8080"
    healthcheck:
      test: ["NONE"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bot-binance]

  bot_hitbtc:
    image: ghcr.io/chidi150c/coinbase-bot:latest
    command: ["-live", "-interval", "1"]
    volumes:
      - /opt/coinbase/env:/opt/coinbase/env:ro
      - /opt/coinbase/state:/opt/coinbase/state
    env_file:
      - /opt/coinbase/env/bot.env
      - /opt/coinbase/env/hitbtc.env          # HITBTC_API_KEY/SECRET, base URL, sandbox flag
      - /opt/coinbase/env/bot_hitbtc.env      # broker/product/state overrides for HitBTC
    restart: unless-stopped
    expose:
      - "8080"
    healthcheck:
      test: ["NONE"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      monitoring_network:
        aliases: [bot-hitbtc]

  prometheus:
    image: prom/prometheus:latest
    ports: ["9090:9090"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - monitoring_prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
      - --storage.tsdb.retention.size=2GB
    restart: unless-stopped
    networks: [monitoring_network]

  alertmanager:
    image: prom/alertmanager:latest
    ports: ["9093:9093"]
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped
    networks: [monitoring_network]

  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - monitoring_grafana_data:/var/lib/grafana
    depends_on: [prometheus, bot, bridge]
    networks: [monitoring_network]

volumes:
  monitoring_prometheus_data:
  monitoring_grafana_data:
  coinbase_state:

networks:
  monitoring_network:
    driver: bridge
