name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  go-ci:
    name: Go vet & test
    runs-on: ubuntu-latest
    env:
      IMAGE_SHA: ${{ github.sha }}
      # Default GHCR_NS to repo owner if org-level var isn't set (e.g., on forks/PRs)
      GHCR_NS: ${{ vars.GHCR_NS || github.repository_owner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rewrite monitoring/docker-compose.yml image refs (namespace + bot tag)
        shell: bash
        run: |
          set -euo pipefail
          f="monitoring/docker-compose.yml"
          if [[ -f "$f" ]]; then
            # Replace hard-coded namespace with ghcr.io/${GHCR_NS:-chidi150c}
            sed -i 's#ghcr.io/chidi150c/#ghcr.io/${GHCR_NS:-chidi150c}/#g' "$f"
            # Tag all bot services with ${IMAGE_SHA} instead of :latest
            sed -i 's#\(ghcr.io/${GHCR_NS:-chidi150c}/coinbase-bot\):latest#\1:${IMAGE_SHA}#g' "$f"
          fi
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.x"
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -count=1 ./...
