name: Deploy to Linode

on:
  workflow_run:
    workflows: ["Build & Push Images"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency:
      group: prod-deploy
      cancel-in-progress: false

    steps:
      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          install -m 700 -d ~/.ssh
          printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy (git sync + compose rollout)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}   # e.g. /home/chidi/coinbase/monitoring
          REPO_URL:   https://github.com/${{ github.repository }}.git
          GIT_SHA:    ${{ github.sha }}
          HUMAN_TAG:  ${{ github.ref_name }}
          GHCR_NS:    ${{ vars.GHCR_NS }}
        run: |
          ssh -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" bash -s -- "$DEPLOY_DIR" "$REPO_URL" "$GIT_SHA" "$HUMAN_TAG" "$GHCR_NS" <<'EOF'
          set -euo pipefail
          DEPLOY_DIR="${1:-/home/chidi/coinbase/monitoring}"
          REPO_URL="$2"
          GIT_SHA_IN="$3"
          HUMAN_TAG_IN="$4"
          GHCR_NS_IN="${5:-}"
          REPO_DIR="$(dirname "$DEPLOY_DIR")"

          # Sync repo
          if [ ! -d "$REPO_DIR/.git" ]; then
            mkdir -p "$REPO_DIR"
            git clone "$REPO_URL" "$REPO_DIR"
          else
            git -C "$REPO_DIR" remote set-url origin "$REPO_URL"
            git -C "$REPO_DIR" fetch --all
            git -C "$REPO_DIR" reset --hard origin/main
          fi

          cd "$DEPLOY_DIR"

          # Patch docker-compose image namespace and bot tags (idempotent)
          # - Replace ghcr.io/chidi150c with ghcr.io/${GHCR_NS:-chidi150c}
          # - Tag all bot images with ${IMAGE_SHA}
          if [ -f docker-compose.yml ]; then
            sed -i 's#ghcr.io/chidi150c/#ghcr.io/${GHCR_NS:-chidi150c}/#g' docker-compose.yml
            sed -i 's#\(ghcr.io/${GHCR_NS:-chidi150c}/coinbase-bot\):latest#\1:${IMAGE_SHA}#g' docker-compose.yml
          fi

          # Inject CI/CD identity into runtime (compose can reference these)
          # IMAGE_SHA kept equal to GIT_SHA to preserve existing naming.
          cat > .env.ci <<ENVVARS
          GIT_SHA=${GIT_SHA_IN}
          IMAGE_SHA=${GIT_SHA_IN}
          HUMAN_TAG=${HUMAN_TAG_IN}
          GHCR_NS=${GHCR_NS_IN}
          ENVVARS

          # --- Minimal additions to guarantee clean rollout with fresh images ---

          # Selective services to bounce (do not touch prometheus/grafana)
          SERVICES=(bot_binance bot bridge_binance bridge)

          # Stop & remove the target services (containers only)
          docker compose --env-file .env.ci stop "\${SERVICES[@]}" || true
          docker compose --env-file .env.ci rm -f "\${SERVICES[@]}" || true

          # Force-remove only our project images so we never reuse an old local image
          REPO_BOT="ghcr.io/\${GHCR_NS:-chidi150c}/coinbase-bot"
          REPO_BRIDGE="ghcr.io/\${GHCR_NS:-chidi150c}/coinbase-bridge"
          REPO_BRIDGE_BN="ghcr.io/\${GHCR_NS:-chidi150c}/coinbase-bridge-binance"

          for repo in "\$REPO_BOT" "\$REPO_BRIDGE" "\$REPO_BRIDGE_BN"; do
            ids=\$(docker image ls "\$repo" --format '{{.ID}}' | sort -u)
            if [ -n "\$ids" ]; then
              echo "[deploy] removing local images for \$repo"
              echo "\$ids" | xargs -r docker image rm -f || true
            fi
          done

          # Clean dangling layers/cache (safe)
          docker image prune -f || true
          docker builder prune -f || true

          # Pre-pull images for the target services (honors IMAGE_SHA)
          docker compose --env-file .env.ci pull "\${SERVICES[@]}"

          # Rollout with full recreate (guaranteed fresh images)
          docker compose --env-file .env.ci up -d --force-recreate "\${SERVICES[@]}"

          # Optional hygiene after rollout
          docker image prune -f || true
          EOF
