name: Deploy to Linode

on:
  workflow_run:
    workflows: ["Build & Push Images"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency:
      group: prod-deploy
      cancel-in-progress: false

    steps:
      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          install -m 700 -d ~/.ssh
          printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy (git sync + compose rollout with pre-launch prune)
        env:
          SSH_HOST:   ${{ secrets.SSH_HOST }}
          SSH_USER:   ${{ secrets.SSH_USER }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}   # e.g. /home/chidi/coinbase/monitoring
          REPO_URL:   https://github.com/${{ github.repository }}.git
          GIT_SHA:    ${{ github.sha }}
          HUMAN_TAG:  ${{ github.ref_name }}
          GHCR_NS:    ${{ vars.GHCR_NS }}
        run: |
          ssh -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" bash -s -- "$DEPLOY_DIR" "$REPO_URL" "$GIT_SHA" "$HUMAN_TAG" "$GHCR_NS" <<'EOF'
          set -euo pipefail

          DEPLOY_DIR="${1:-/home/chidi/coinbase/monitoring}"
          REPO_URL="$2"
          GIT_SHA_IN="$3"
          HUMAN_TAG_IN="$4"
          GHCR_NS_IN="${5:-}"
          : "${GHCR_NS_IN:=chidi150c}"

          REPO_DIR="$(dirname "$DEPLOY_DIR")"

          # --- 1) Sync repo ---
          if [ ! -d "$REPO_DIR/.git" ]; then
            mkdir -p "$REPO_DIR"
            git clone "$REPO_URL" "$REPO_DIR"
          else
            git -C "$REPO_DIR" remote set-url origin "$REPO_URL"
            git -C "$REPO_DIR" fetch --all
            git -C "$REPO_DIR" reset --hard origin/main
          fi

          cd "$DEPLOY_DIR"

          # --- 2) Patch docker-compose.yml (namespace + tag pinning) ---
          # Replace ghcr.io/chidi150c with templated namespace
          if [ -f docker-compose.yml ]; then
            sed -i 's#ghcr.io/chidi150c/#ghcr.io/${GHCR_NS:-chidi150c}/#g' docker-compose.yml
            # Pin bot and binance bridge services to ${IMAGE_SHA}
            sed -i 's#\(ghcr.io/${GHCR_NS:-chidi150c}/coinbase-bot\):.*#\1:${IMAGE_SHA}#g' docker-compose.yml
            sed -i 's#\(ghcr.io/${GHCR_NS:-chidi150c}/coinbase-bridge-binance\):.*#\1:${IMAGE_SHA}#g' docker-compose.yml
            # Leave the generic bridge service on :latest as you requested
          fi

          # --- 3) Inject CI env for compose ---
          cat > .env.ci <<ENVVARS
          GIT_SHA=${GIT_SHA_IN}
          IMAGE_SHA=${GIT_SHA_IN}
          HUMAN_TAG=${HUMAN_TAG_IN}
          GHCR_NS=${GHCR_NS_IN}
          ENVVARS

          # --- 4) Bring down stack BEFORE pruning images ---
          # This ensures no image is "in use" so we can prune ALL old tags.
          docker compose --env-file .env.ci down --remove-orphans || true

          # --- 5) PRUNE ALL OLD IMAGES (repo-scoped hard prune) BEFORE LAUNCH ---
          # We remove ALL local images for these repos so compose will re-pull fresh tags.
          # This is stronger than 'prune dangling' and matches your requirement.
          REPOS=(
            "coinbase-bot"
            "coinbase-bridge-binance"
            "coinbase-bridge"
            "coinbase-bridge-hitbtc"
          )

          for r in "${REPOS[@]}"; do
            # Remove ALL images for each repo, regardless of tag
            # Safe now because containers are down.
            IDS=$(docker image ls -q "ghcr.io/${GHCR_NS_IN}/${r}" || true)
            if [ -n "${IDS:-}" ]; then
              echo "Removing images for ghcr.io/${GHCR_NS_IN}/${r}:"
              echo "${IDS}" | xargs -r docker image rm -f
            fi
          done

          # Optional: also clear dangling layers after the hard prune
          docker image prune -af || true

          # --- 6) Launch fresh (pull always, force recreate) ---
          docker compose --env-file .env.ci up -d --pull=always --force-recreate

          # --- 7) Quick sanity: show what actually launched ---
          echo
          echo "== Running containers =="
          docker ps --format 'table {{.Names}}\t{{.Image}}\t{{.Status}}'
          echo
          echo "== Compose images =="
          docker compose --env-file .env.ci images
          EOF
