name: Deploy to Linode

on:
  workflow_run:
    workflows: ["Build & Push Images"]
    types: [completed]
    branches: ["main"]
  workflow_dispatch: {}  # allow manual runs

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency:
      group: prod-deploy
      cancel-in-progress: false

    steps:
      - name: Prepare SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          install -m 700 -d ~/.ssh
          printf "%s" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add host to known_hosts
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Deploy (pull & up)
        env:
          SSH_HOST:  ${{ secrets.SSH_HOST }}
          SSH_USER:  ${{ secrets.SSH_USER }}
          DEPLOY_DIR: ${{ vars.DEPLOY_DIR }}            # e.g. /home/chidi/coinbase/monitoring
          GHCR_USER: ${{ github.repository_owner }}     # used only if GHCR_PAT is set
          GHCR_PAT:  ${{ secrets.GHCR_PAT }}            # optional; set if GHCR packages are private
        run: |
          ssh -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" bash -s -- "$DEPLOY_DIR" "$GHCR_USER" "$GHCR_PAT" <<'EOF'
          set -euo pipefail
          DEPLOY_DIR="${1:-/home/chidi/coinbase/monitoring}"
          GHCR_USER="${2:-}"
          GHCR_PAT="${3:-}"

          # If a PAT is provided (private GHCR), log in before pulling
          if [ -n "$GHCR_PAT" ]; then
            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
          fi

          cd "$DEPLOY_DIR"
          docker compose pull
          docker compose up -d
          docker image prune -f
          EOF
