name: Build & Push Images

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  BOT_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bot
  BRIDGE_BINANCE_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bridge-binance
  BRIDGE_HITBTC_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bridge-hitbtc

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Bot image
      - name: Build & push bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.BOT_IMAGE }}:latest
            ${{ env.BOT_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Bridge (Binance) image
      - name: Build & push bridge (binance)
        uses: docker/build-push-action@v5
        with:
          context: ./bridge_binance
          file: ./bridge_binance/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.BRIDGE_BINANCE_IMAGE }}:latest
            ${{ env.BRIDGE_BINANCE_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Bridge (HitBTC) image
      - name: Build & push bridge (hitbtc)
        uses: docker/build-push-action@v5
        with:
          context: ./bridge_hitbtc
          file: ./bridge_hitbtc/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.BRIDGE_HITBTC_IMAGE }}:latest
            ${{ env.BRIDGE_HITBTC_IMAGE }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
