name: Build & Push Images

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  GIT_SHA: ${{ github.sha }}
  HUMAN_TAG: ${{ github.ref_name }}
  BOT_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bot
  BRIDGE_BINANCE_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bridge-binance
  BRIDGE_HITBTC_IMAGE: ghcr.io/${{ github.repository_owner }}/coinbase-bridge-hitbtc
  PUSH_LATEST: ${{ github.ref == 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --------------------------
      # Bot image
      # --------------------------
      - name: Build & push bot
        id: build_bot
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          pull: true
          no-cache: true
          tags: |
            ${{ env.BOT_IMAGE }}:${{ env.GIT_SHA }}
            ${{ env.BOT_IMAGE }}:${{ env.HUMAN_TAG }}
            ${{ env.BOT_IMAGE }}:latest${{ env.PUSH_LATEST && '' || '-skip' }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ env.GIT_SHA }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          build-args: |
            GIT_SHA=${{ env.GIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trim bogus -skip tag for bot (no-op if not present)
        if: ${{ always() }}
        run: |
          docker buildx imagetools inspect "${{ env.BOT_IMAGE }}:latest-skip" >/dev/null 2>&1 && \
          docker buildx imagetools rm "${{ env.BOT_IMAGE }}:latest-skip" || true

      # --------------------------
      # Bridge (Binance) image
      # --------------------------
      - name: Build & push bridge (binance)
        id: build_binance
        uses: docker/build-push-action@v5
        with:
          context: ./bridge_binance
          file: ./bridge_binance/Dockerfile
          push: true
          platforms: linux/amd64
          pull: true
          no-cache: true
          tags: |
            ${{ env.BRIDGE_BINANCE_IMAGE }}:${{ env.GIT_SHA }}
            ${{ env.BRIDGE_BINANCE_IMAGE }}:${{ env.HUMAN_TAG }}
            ${{ env.BRIDGE_BINANCE_IMAGE }}:latest${{ env.PUSH_LATEST && '' || '-skip' }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ env.GIT_SHA }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          build-args: |
            GIT_SHA=${{ env.GIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trim bogus -skip tag for bridge (binance) (no-op if not present)
        if: ${{ always() }}
        run: |
          docker buildx imagetools inspect "${{ env.BRIDGE_BINANCE_IMAGE }}:latest-skip" >/dev/null 2>&1 && \
          docker buildx imagetools rm "${{ env.BRIDGE_BINANCE_IMAGE }}:latest-skip" || true

      # --------------------------
      # Bridge (HitBTC) image
      # --------------------------
      - name: Build & push bridge (hitbtc)
        id: build_hitbtc
        uses: docker/build-push-action@v5
        with:
          context: ./bridge_hitbtc
          file: ./bridge_hitbtc/Dockerfile
          push: true
          platforms: linux/amd64
          pull: true
          no-cache: true
          tags: |
            ${{ env.BRIDGE_HITBTC_IMAGE }}:${{ env.GIT_SHA }}
            ${{ env.BRIDGE_HITBTC_IMAGE }}:${{ env.HUMAN_TAG }}
            ${{ env.BRIDGE_HITBTC_IMAGE }}:latest${{ env.PUSH_LATEST && '' || '-skip' }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ env.GIT_SHA }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
          build-args: |
            GIT_SHA=${{ env.GIT_SHA }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trim bogus -skip tag for bridge (hitbtc) (no-op if not present)
        if: ${{ always() }}
        run: |
          docker buildx imagetools inspect "${{ env.BRIDGE_HITBTC_IMAGE }}:latest-skip" >/dev/null 2>&1 && \
          docker buildx imagetools rm "${{ env.BRIDGE_HITBTC_IMAGE }}:latest-skip" || true
